### ISSUE TITLE
Code Project Assignment

### ISSUE THREAD

**Issue by Phan717** [Phan717/web-design-2-independent-project#16]
Hi Christian,
I have tried to finish coding my independent project and submit through Makbot. However, it still appeared the test passed 94%, and failed 2 tests (pls see the attached screenshot). I tried to figure out but I cannot. Is it possible if I receive part-marks? Can you help me to figure it out? Thank you.
@thatkidmadrid

<img width="807" alt="Screen Shot 2021-12-15 at 15 11 34" src="https://user-images.githubusercontent.com/76163382/146260961-c6d1514e-2320-412d-bc50-ddcf96038d1a.png">

**Comment by thatkidmadrid** [comment]
Can you show the error messages that appear on markbot?

**Comment by thatkidmadrid** [comment]
if it doesn't pass markbot I can't give marks on the rubric towards the markbot completion. It's either passes or doesn't pass. I'll try to help you out but you need to provide more information

**Comment by Phan717** [comment]
<img width="802" alt="Screen Shot 2021-12-15 at 15 41 02" src="https://user-images.githubusercontent.com/76163382/146261934-f40e95e6-224b-4f58-9cb2-542ff66760f4.png">
<img width="798" alt="Screen Shot 2021-12-15 at 15 41 16" src="https://user-images.githubusercontent.com/76163382/146261939-8b256336-85f1-4067-8f27-a2581fb87c8b.png">
<img width="800" alt="Screen Shot 2021-12-15 at 15 41 27" src="https://user-images.githubusercontent.com/76163382/146261941-d06960e2-6d9b-4498-b5ba-8037cbdd89d9.png">

@thatkidmadrid

**Comment by thatkidmadrid** [comment]
We went over favicons in class so I will encourage you to go back to i think its week 13 if you want to see an example of how to do it. Instead of using the links in the lesson, use this site instead to create your .ico file https://favicon.io/favicon-converter/

here is the written lesson for favicons: https://learn-the-web.algonquindesign.ca/topics/image-formats/#favicons

Here is the cheatsheet that shows how to do the skip links. You just need to follow the instructions that markbot is telling you (ie. it needs to be the first element in your `<body>` tag)

Just follow markbot's instructions for the indentation error

you can remove the aria role from your image. it's not necessary here.

Here is the tool to check your colour contrast: https://webaim.org/resources/contrastchecker/

Here is the lesson to go over hover/focus styles and why it's important to use styles make it obvious when they are hovered/have focus. https://learn-the-web.algonquindesign.ca/topics/accessibility-for-design/#keyboard-focus-styles

Follow markbot's instruction about the main link focus. You need an example of some sort of link somewhere in either a `main`, `section`, or `article`
